### ISSUE TITLE
Would you like to share the preprocessing code for the remaining datasets? (ETH-UCY and SDD)

### ISSUE THREAD

**Issue by SeongjuLee** [MediaBrain-SJTU/GroupNet#1]
I am really impressed with your research "GroupNet: Multiscale Hypergraph Neural Networks for Trajectory Prediction with Relational Reasoning" which is accepted in CVPR2022!
I would like to thank if your share the preprocessing code for other datasets.
Thanks! 👍

**Comment by sjtuxcx** [comment]
Thank you for your interest in our work! We will release the code on SDD/ETH-UCY afterward. As only for the preprocessing code, you can refer to [PECNet](https://github.com/HarshayuGirase/Human-Path-Prediction/tree/master/PECNet) and [Agentformer](https://github.com/Khrylx/AgentFormer). Our preprocessing code is slightly modified from these two repositories.

**Comment by SeongjuLee** [comment]
Thanks for your reply.

**Comment by daeunni** [comment]
Hi, @sjtuxcx 
Thanks for your impressive work! 
Do you have plans to release the codes of SDD/ETH-UCY? 

Best, 
Daeun Lee
