### ISSUE TITLE
NFL dataset

### ISSUE THREAD

**Issue by Carrotsniper** [MediaBrain-SJTU/GroupNet#10]
Hi, thanks for your excellent work, may I ask where did you download the NFL football dataset?

**Comment by sjtuxcx** [comment]
Thanks for your interest in our work! The source dataset comes from [Link](https://github.com/nfl-football-ops/Big-Data-Bowl). Furthermore, if you want to align the dataset situation with ours, you can provide an email address and I will send you the processed data.

**Comment by Carrotsniper** [comment]
Thanks for your response. Below is my e-mail address:

sc16rl@gmail.com

Thanks for sharing.
