### ISSUE TITLE
Wrong loss calculation 

### ISSUE THREAD

**Issue by danyayay** [MediaBrain-SJTU/GroupNet#2]
Dear authors, 

There seems a wrong calculation of loss in your code. You averaged the loss (pred, recover, diverse) over batch size and pred.shape[0], but pred.shape[0] already includes batch size. However, the sequence dimension was not averaged. Also, you multiplied agent_num for kl loss. The performance can be further improved after correction.

**Comment by sjtuxcx** [comment]
Sorry for the late reply. Thank you for spotting this! Sorry we have mistakes in cleaning the code. Yes, the pred.shape[0] should be pred.shape[1]. We will correct the loss part of the code soon.
