### ISSUE TITLE
Handling variable number of pedestrians

### ISSUE THREAD

**Issue by theDebugger811** [MediaBrain-SJTU/GroupNet#4]
Hello,
        This is really exciting work and thanks for open-sourcing the code. I wanted to use the interaction module on other datasets (e.g. ETH/UCY, TrajNet++) which have a variable number of pedestrians in each sample. Example: Sample 1 can have five pedestrians, and Sample 2 can have four pedestrians. How can I use the `MS_HGNN` module in this case? 

I believe the current implementation assumes that the number of pedestrians is constant for each sample across entire dataset. This is true for NBA but not for the other datasets.

Thanks!

**Comment by sjtuxcx** [comment]
Hi, thanks for your question and interest in our work! Yes, here we release the version of MS_HGNN to handle different scenes simultaneously in a batch. If the number of pedestrians varies, you need to treat scenes serially by changing input data to the size of [agent_num, T, 2] and perform MS-HGNN on the agent_num dimension. We will try to release the implementation on SDD afterward but maybe need some time. If you have any other questions, please let me know.

**Comment by theDebugger811** [comment]
Thanks for your reply. One small follow-up. According to your suggestion:
1. Do I treat each scene independently (i.e. batch_size = 1)?
OR
2. Should I manually fix the value of `agent_num`? i.e. I fix it to be 5 (consider only the pedestrian of interest and its four nearest neighbors). If this is what you suggest, what should be done if the number of neighbors is less than 4?

Thanks!

**Comment by sjtuxcx** [comment]
Thanks for your question. You can treat each scene independently (i.e. batch_size = 1, but here no need for the batch dimension). Also, in one scene you can fix the agent_num as you said in 2.  If the number of neighbors is less than the fixed number, you can have zero padding to it.

**Comment by HongKongDoll2** [comment]
> Thanks for your reply. One small follow-up. According to your suggestion:
> 
> 1. Do I treat each scene independently (i.e. batch_size = 1)?
>    OR
> 2. Should I manually fix the value of `agent_num`? i.e. I fix it to be 5 (consider only the pedestrian of interest and its four nearest neighbors). If this is what you suggest, what should be done if the number of neighbors is less than 4?
> 
> Thanks!

Hi!bro,
  I also want to use the MS_HGNN modules on other datasets which has variable nodes,so have you already solved the problems?

Thanks
